### ISSUE TITLE
Help text for Discord bot

### ISSUE THREAD

**Issue by Lapi492** [munhyunsu/SalmonRunTweetbot#14]
Update help text by following and delete kbb command (because it's difficult to both use and explain)

SalmonRun Reminder KR

LuHaCommands:
  dice      주사위를 굴립니다. “!주사위 [횟수(숫자)]D[면체(숫자)]”
  fortune   타로카드를 하나 뽑습니다. 타로 뒤에 문자열을 적을 수 있습니다. “!타로 (문자열)”
  hello     인사를 합니다. “!hello”
  kbb       사용법: 가위바위보 가위 -> 가위바위보 결과
  rps      봇과 가위바위보를 합니다. “![가위or바위or보]”
  search    해당 검색엔진에서 검색어로 검색한 링크를 줍니다. “!검색 [구글or네이버or다음] [검색어]”
  select    띄어쓰기로 구분된 단어들 중에서 하나를 선택합니다. 단어는 2개 이상이어야 합니다. “!선택 [선택지1] [선택지2] [선택지3]”
SplatoonCommands:
  league    리그 배틀 스테이지를 확인합니다. “!리그”
  meme      짤방을 무작위로 호출합니다. “!짤”
  ranked    랭크 배틀 스테이지를 확인합니다. “!랭크”
  regular   레귤러/나와바리 배틀 스테이지를 확인합니다. “![나와바리or일반]”
  salmonrun 연어런 알림 봇의 최신 트윗을 가져옵니다. “!연어”
  weapon    무작위 무기를 호출합니다. “!무기”
​No Category:
  help      지금 보고 있는 도움말을 표시합니다. “!help”

Type !help command for more info on a command.
You can also type !help category for more info on a category.

**Comment by munhyunsu** [comment]
Resolved https://github.com/munhyunsu/SalmonRunTweetbot/commit/2eff4f14941d0ada069ac1d8057e9f6cc652e0c6
